#############################################################################
# Makefile for building: DSS-Q.app/Contents/MacOS/DSS-Q
# Generated by qmake (2.01a) (Qt 4.8.1) on: Mon Feb 18 21:30:35 2013
# Project:  DSS-Q.pro
# Template: app
# Command: /Users/blazovics/QtSDK/Desktop/Qt/4.8.1/gcc/bin/qmake -spec ../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/macx-g++ CONFIG+=declarative_debug -o Makefile DSS-Q.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DECLARATIVE_DEBUG -DQT_DECLARATIVE_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/macx-g++ -I. -I../../QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtCore.framework/Versions/4/Headers -I../../QtSDK/Desktop/Qt/4.8.1/gcc/include/QtCore -I../../QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtGui.framework/Versions/4/Headers -I../../QtSDK/Desktop/Qt/4.8.1/gcc/include/QtGui -I../../QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtXml.framework/Versions/4/Headers -I../../QtSDK/Desktop/Qt/4.8.1/gcc/include/QtXml -I../../QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtDeclarative.framework/Versions/4/Headers -I../../QtSDK/Desktop/Qt/4.8.1/gcc/include/QtDeclarative -I../../QtSDK/Desktop/Qt/4.8.1/gcc/include -Iqmlapplicationviewer -I. -F/Users/blazovics/QtSDK/Desktop/Qt/4.8.1/gcc/lib
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS) -F/Users/blazovics/QtSDK/Desktop/Qt/4.8.1/gcc/lib -L/Users/blazovics/QtSDK/Desktop/Qt/4.8.1/gcc/lib -framework QtDeclarative -L/usr/local/pgsql/lib -L/tmp/qt-stuff-85167/source/qt-everywhere-opensource-src-4.8.1/Desktop/Qt/4.8.1/gcc/lib -F/tmp/qt-stuff-85167/source/qt-everywhere-opensource-src-4.8.1/Desktop/Qt/4.8.1/gcc/lib -framework QtScript -framework QtCore -framework QtSvg -framework QtGui -framework QtSql -framework QtXmlPatterns -framework QtNetwork -framework QtXml 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /Users/blazovics/QtSDK/Desktop/Qt/4.8.1/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		entity.cpp \
		field.cpp \
		place.cpp \
		logger.cpp \
		scene.cpp \
		QT_UI/screenwidget.cpp \
		renderobject.cpp \
		swarmentity.cpp \
		grgentity.cpp \
		QT_UI/toolbarwidget.cpp \
		targetentity.cpp \
		qmlapplicationviewer/qmlapplicationviewer.cpp moc_qmlapplicationviewer.cpp \
		moc_screenwidget.cpp \
		moc_toolbarwidget.cpp
OBJECTS       = main.o \
		entity.o \
		field.o \
		place.o \
		logger.o \
		scene.o \
		screenwidget.o \
		renderobject.o \
		swarmentity.o \
		grgentity.o \
		toolbarwidget.o \
		targetentity.o \
		qmlapplicationviewer.o \
		moc_qmlapplicationviewer.o \
		moc_screenwidget.o \
		moc_toolbarwidget.o
DIST          = ../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/mac.conf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-macx.conf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-macx.conf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_pre.prf \
		qmlapplicationviewer/qmlapplicationviewer.pri \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/dwarf2.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/debug.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_post.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/x86_64.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/objective_c.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/declarative_debug.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/rez.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/sdk.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf \
		DSS-Q.pro
QMAKE_TARGET  = DSS-Q
DESTDIR       = 
TARGET        = DSS-Q.app/Contents/MacOS/DSS-Q

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile DSS-Q.app/Contents/PkgInfo DSS-Q.app/Contents/Resources/empty.lproj DSS-Q.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) DSS-Q.app/Contents/MacOS/ || $(MKDIR) DSS-Q.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: DSS-Q.pro  ../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/macx-g++/qmake.conf ../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/mac.conf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-macx.conf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-macx.conf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_pre.prf \
		qmlapplicationviewer/qmlapplicationviewer.pri \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/dwarf2.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/debug.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_post.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/x86_64.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/objective_c.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/declarative_debug.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/rez.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/sdk.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf \
		../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf \
		/Users/blazovics/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtDeclarative.framework/QtDeclarative.prl \
		/Users/blazovics/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtScript.framework/QtScript.prl \
		/Users/blazovics/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtCore.framework/QtCore.prl \
		/Users/blazovics/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtSvg.framework/QtSvg.prl \
		/Users/blazovics/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtGui.framework/QtGui.prl \
		/Users/blazovics/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtSql.framework/QtSql.prl \
		/Users/blazovics/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtXmlPatterns.framework/QtXmlPatterns.prl \
		/Users/blazovics/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtNetwork.framework/QtNetwork.prl \
		/Users/blazovics/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtXml.framework/QtXml.prl
	$(QMAKE) -spec ../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/macx-g++ CONFIG+=declarative_debug -o Makefile DSS-Q.pro
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/mac.conf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-macx.conf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-macx.conf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_pre.prf:
qmlapplicationviewer/qmlapplicationviewer.pri:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/dwarf2.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/debug.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_post.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/x86_64.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/objective_c.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/declarative_debug.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/rez.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/sdk.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf:
../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf:
/Users/blazovics/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtDeclarative.framework/QtDeclarative.prl:
/Users/blazovics/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtScript.framework/QtScript.prl:
/Users/blazovics/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtCore.framework/QtCore.prl:
/Users/blazovics/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtSvg.framework/QtSvg.prl:
/Users/blazovics/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtGui.framework/QtGui.prl:
/Users/blazovics/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtSql.framework/QtSql.prl:
/Users/blazovics/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtXmlPatterns.framework/QtXmlPatterns.prl:
/Users/blazovics/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtNetwork.framework/QtNetwork.prl:
/Users/blazovics/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtXml.framework/QtXml.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/macx-g++ CONFIG+=declarative_debug -o Makefile DSS-Q.pro

DSS-Q.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) DSS-Q.app/Contents || $(MKDIR) DSS-Q.app/Contents 
	@$(DEL_FILE) DSS-Q.app/Contents/PkgInfo
	@echo "APPL????" >DSS-Q.app/Contents/PkgInfo
DSS-Q.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) DSS-Q.app/Contents/Resources || $(MKDIR) DSS-Q.app/Contents/Resources 
	@touch DSS-Q.app/Contents/Resources/empty.lproj
	
DSS-Q.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) DSS-Q.app/Contents || $(MKDIR) DSS-Q.app/Contents 
	@$(DEL_FILE) DSS-Q.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,DSS-Q,g" -e "s,@TYPEINFO@,????,g" ../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/macx-g++/Info.plist.app >DSS-Q.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/DSS-Q1.0.0 || $(MKDIR) .tmp/DSS-Q1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/DSS-Q1.0.0/ && $(COPY_FILE) --parents qmlapplicationviewer/qmlapplicationviewer.h entity.h field.h place.h common.h logger.h scene.h QT_UI/screenwidget.h maths.h renderobject.h swarmentity.h grgentity.h QT_UI/toolbarwidget.h targetentity.h .tmp/DSS-Q1.0.0/ && $(COPY_FILE) --parents main.cpp entity.cpp field.cpp place.cpp logger.cpp scene.cpp QT_UI/screenwidget.cpp renderobject.cpp swarmentity.cpp grgentity.cpp QT_UI/toolbarwidget.cpp targetentity.cpp qmlapplicationviewer/qmlapplicationviewer.cpp .tmp/DSS-Q1.0.0/ && (cd `dirname .tmp/DSS-Q1.0.0` && $(TAR) DSS-Q1.0.0.tar DSS-Q1.0.0 && $(COMPRESS) DSS-Q1.0.0.tar) && $(MOVE) `dirname .tmp/DSS-Q1.0.0`/DSS-Q1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/DSS-Q1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r DSS-Q.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_qmlapplicationviewer.cpp moc_screenwidget.cpp moc_toolbarwidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qmlapplicationviewer.cpp moc_screenwidget.cpp moc_toolbarwidget.cpp
moc_qmlapplicationviewer.cpp: qmlapplicationviewer/qmlapplicationviewer.h
	/Users/blazovics/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ qmlapplicationviewer/qmlapplicationviewer.h -o moc_qmlapplicationviewer.cpp

moc_screenwidget.cpp: QT_UI/screenwidget.h
	/Users/blazovics/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ QT_UI/screenwidget.h -o moc_screenwidget.cpp

moc_toolbarwidget.cpp: QT_UI/toolbarwidget.h
	/Users/blazovics/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ QT_UI/toolbarwidget.h -o moc_toolbarwidget.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp common.h \
		maths.h \
		scene.h \
		QT_UI/screenwidget.h \
		QT_UI/toolbarwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

entity.o: entity.cpp entity.h \
		common.h \
		maths.h \
		renderobject.h \
		place.h \
		logger.h \
		field.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o entity.o entity.cpp

field.o: field.cpp field.h \
		common.h \
		maths.h \
		place.h \
		renderobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o field.o field.cpp

place.o: place.cpp place.h \
		common.h \
		maths.h \
		renderobject.h \
		field.h \
		entity.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o place.o place.cpp

logger.o: logger.cpp logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logger.o logger.cpp

scene.o: scene.cpp scene.h \
		common.h \
		maths.h \
		field.h \
		entity.h \
		renderobject.h \
		place.h \
		targetentity.h \
		swarmentity.h \
		grgentity.h \
		playerentity.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scene.o scene.cpp

screenwidget.o: QT_UI/screenwidget.cpp QT_UI/screenwidget.h \
		scene.h \
		common.h \
		maths.h \
		field.h \
		entity.h \
		renderobject.h \
		place.h \
		targetEntity.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o screenwidget.o QT_UI/screenwidget.cpp

renderobject.o: renderobject.cpp renderobject.h \
		common.h \
		maths.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o renderobject.o renderobject.cpp

swarmentity.o: swarmentity.cpp swarmentity.h \
		entity.h \
		common.h \
		maths.h \
		renderobject.h \
		place.h \
		field.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o swarmentity.o swarmentity.cpp

grgentity.o: grgentity.cpp grgentity.h \
		entity.h \
		common.h \
		maths.h \
		renderobject.h \
		place.h \
		field.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o grgentity.o grgentity.cpp

toolbarwidget.o: QT_UI/toolbarwidget.cpp QT_UI/toolbarwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o toolbarwidget.o QT_UI/toolbarwidget.cpp

targetentity.o: targetentity.cpp targetentity.h \
		entity.h \
		common.h \
		maths.h \
		renderobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o targetentity.o targetentity.cpp

qmlapplicationviewer.o: qmlapplicationviewer/qmlapplicationviewer.cpp qmlapplicationviewer/qmlapplicationviewer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qmlapplicationviewer.o qmlapplicationviewer/qmlapplicationviewer.cpp

moc_qmlapplicationviewer.o: moc_qmlapplicationviewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qmlapplicationviewer.o moc_qmlapplicationviewer.cpp

moc_screenwidget.o: moc_screenwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_screenwidget.o moc_screenwidget.cpp

moc_toolbarwidget.o: moc_toolbarwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_toolbarwidget.o moc_toolbarwidget.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/DSS-Q/bin/ || $(MKDIR) $(INSTALL_ROOT)/opt/DSS-Q/bin/ 
	$(DEL_FILE) -r "$(INSTALL_ROOT)/opt/DSS-Q/bin/DSS-Q.app"
	
	-$(INSTALL_DIR) "DSS-Q.app" "$(INSTALL_ROOT)/opt/DSS-Q/bin/DSS-Q.app"

uninstall_target:  FORCE
	-$(DEL_FILE) -r "$(INSTALL_ROOT)/opt/DSS-Q/bin/DSS-Q.app"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/DSS-Q/bin/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

